sudo: required
services:
    - docker
    
before_install:
    - docker build -t xabimoreno/koachooweb -f Dockerfile.dev .
script:
    - docker run -u $(id -u) --rm -v "$PWD":/app trion/ng-cli-karma ng test