sudo: required
services:
    - docker    

script:
    - docker build -t xabimoreno/koachooweb -f Dockerfile.dev .
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker"
    env: "Docker-env"
    bucket-name: "elasticbeanstalk-eu-west-1-066900294137"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY