version: '3.5'

services:
    web:    
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '4200:4200'
        volumes: 
            - /app/node_modules
            - .:/app
    angular_karma:
        image: trion/ng-cli-karma:latest
        container_name: "angular_karma"
        volumes:
            - .:/app/
        working_dir: /app/
        ports:
            - 9876:9876
        command: >
            bash -c "ng test"


