FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install
RUN npm install -g @angular/cli

ENV CHROME_BIN /usr/bin/chromium-browser

COPY . .

RUN npm test

CMD ng serve --host 0.0.0.0 --port 4200