FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install
RUN npm install --save-dev @angular-devkit/build-angular
RUN npm install -g @angular/cli
ENV CHROME_BIN /usr/bin/google-chrome

COPY . .

CMD ng serve --host 0.0.0.0 --port 4200